### ISSUE TITLE
usergroup id parent database

### ISSUE THREAD

**Issue by filipw01** [PRD-ev/pytatki#114]
### OPIS BŁĘDU
Note_view nie ma parent_id ani parent_title

### POTENCJALNY SKUTEK BŁĘDU

Nie będzie API dla Reacta :(

### POTENCJALNE ROZWIĄZANIE BŁĘDU

Dodaj do note_view parent_id a jeszcze lepiej jak parent_title

**Comment by butterfly-pn** [comment]
Dodano 'parent_id' i 'parent_name' do v0.4
